### ISSUE TITLE
 BRIDGE Archive 1th OT, 2023-10-05 [22:00]

### ISSUE THREAD

**Issue by fkdl0048** [BRIDGE-DEV/BRIDGE_Archive#1]
#  BRIDGE Archive 1th OT, 2023-10-05 [22:00]

BRIDGE Archive에서 진행하는 첫 OT입니다.

OT는 게더타운에서 진행되며 따로 캠이나 마이크를 준비하지 않으셔도 됩니다.

## 목차

1.  BRIDGE Archive 소개
2. 진행 방식 소개
3. 요일 선정
4. 좋은 글 작성에 관한 이야기
5. Q/A

*OT는 짧게 30분 정도 진행될 예정입니다. OT이후 참여 의사가 있으신 분들을 초대드립니다.*

[OT참여 링크](https://app.gather.town/invite?token=39_HO_-LSJGXN7bAzaw9)

**참여를 희망하시는 분들은 수요조사를 위해 아래 코멘트를 남겨주세요**

**Comment by wooyn730** [comment]
코멘트 남기는 곳 여기 맞나요?
OT 참여 희망합니다!

**Comment by Barone12** [comment]
OT참여 희망합니다!

**Comment by rpopic2** [comment]
참여 희망합니다!! 너무 늦게 봤네요 ㅠㅠ

**Comment by fkdl0048** [comment]
https://app.gather.town/invite?token=qprZRDh8RiWljuOsvfTn

**Comment by fkdl0048** [comment]
https://app.gather.town/invite?token=zYphgjCrQeWJnydVBJF6

**Comment by fkdl0048** [comment]
접속 안되시는 분들은 아래 링크 이용해주세요!
