### ISSUE TITLE
fkdl0048: 우당당탕 Unity PlayMode 문제 해결 과정

### ISSUE THREAD

**Issue by fkdl0048** [BRIDGE-DEV/BRIDGE_Archive#10]
~~이번에는 주차에선 프로젝트에 DI 프레임워크를 도입해볼려고 합니다!~~

최근 개발하다 발생한 알 수 없는? 버그에 해결 방법을 적었습니다.

- [글 링크](https://fkdl0048.github.io/unity/unity_in_PlayModeTestFrameProblem/#%EB%AC%B8%EC%A0%9C-%EB%B0%9C%EC%83%9D)

**Comment by fkdl0048** [comment]
2023-11-30 작성 완

**Comment by rpopic2** [comment]
일단 yield return null이 유니티에서 다음 프레임으로 넘긴다는 것은 당연한 건데, 테스트 코드의, 심지어 플레이 모드에서만 안된다는게.. 내부적으로 그렇게 할 수밖에 없는 이유가 있었겠지만 유니티의 잘못이 아닌가 싶네요. 인터페이스가 일정하지 않으면 사용자가 고생하는 것 같습니다. 동시에 역시 공식 도큐멘트를 잘 읽는 습관을 잘 들여놓아야 한다는 생각이 드네요. 특히 유니티의 경우에는 공식 도큐멘트 안읽고 뒷통수 맞은 경험이 여러 번 있어서 잘 읽고 해야하는 것 같습니다. 해결하시기 까다로우셨을텐데 해결하셨다니 다행이고 좋은 글 잘 읽었습니다!!
