### ISSUE TITLE
rpopic2: [linux] Unity가 켜지지 않을 때

### ISSUE THREAD

**Issue by rpopic2** [BRIDGE-DEV/BRIDGE_Archive#11]
https://www.notion.so/blog-rpopic/linux-Unity-5f4aa2ad9cef401ba4e3c707e8430dbe

짧은 정보글 입니다! 한글로는 찾기 힘든 자료고 최근에 해결한 사항이라 올려 보았습니다.

다른 글 준비중인데 좀 길어져서 이번 주는 짧습니다....ㅋㅋㅋㅠㅠ

**Comment by fkdl0048** [comment]
오.. 리눅스로 유니티를 쓰시고 계시는 군요

가끔 유니티가 켜지고 있을 때 강제 종료하는 프로세스가 궁금했는데 좋은 정보네요

감사합니다!
