### ISSUE TITLE
rpopic2: libpng로 png 파일 로딩하기

### ISSUE THREAD

**Issue by rpopic2** [BRIDGE-DEV/BRIDGE_Archive#12]
https://www.notion.so/blog-rpopic/libpng-png-73cb2f46d3c241f29bd3c4435e515766?pvs=4

이번에는 libpng라는 png 공식 라이브러리로 이미지 파일을 OpenGL에 주기 적합한 형태로 읽어들이는 방법에 대해 써 보았습니다!

**Comment by fkdl0048** [comment]
저도 과거에 42서울에서 저수준 작업을 많이 해봤는데, 그때 당시에 프로그램은 진짜 반복과 분기로만 돌아간다는 사실을 조금 알게되었습니다.

지금 하고 있는 고수준의 작업들이 얼마나 많은 반복인지 헤아릴 수 없겠다고 생각했던 것 같네요.. 디버깅도 되게 깊게 들어가지만 그 코드 자체도 고수준이니 실제 내부는 얼마나 깊을지.. 빙산의 일각..

아마 제가 배우고 있는 OpenGL은 대부분 기능적인 영역이라 다른 것 같습니다.

OpenGL이 column major라는 사실 때문에 실제 mat 계산에 대해서 전치행렬로 계산하는게 생각나네요

```c
for (size_t i = size; i-- > 0;) {}
```

이건 진짜 처음 보네요

작성하신 글 마다 제가 궁금했던 내용들이라 너무 좋습니다~!

**Comment by rpopic2** [comment]
`for (size_t i = size - 1; i < size; --i) {}`

최근에 알게 되었는데 이런 방법이 있더군요..!
