### ISSUE TITLE
rpopic: 버튼 클릭시 UnityAction에서 NullReferenceException이 뜰 때

### ISSUE THREAD

**Issue by rpopic2** [BRIDGE-DEV/BRIDGE_Archive#13]
좀 어이없는 실수인데 디버깅하는데 은근 시간이 걸렸던 문제라서 공유합니다~

https://www.notion.so/blog-rpopic/UnityAction-NullReferenceException-8483efb42ba1468ab4aadc8f761d7c55?pvs=4

**Comment by fkdl0048** [comment]
오.. 이런 에러는 처음 봐서 신기하네요..

해당 함수의 기본 매개변수가 null일 조건이 다른 필요한 경우가 있어서 하신게 맞을까요?

없다면 where를 통해서나 값을 제한 하는 방법도 좋을 것 같은데, 아마 action 자체도 null을 필요로 하셔서 작업하신 것 같네요

is를 통한 null 조건도 좋아보입니다! 

저의 경우엔.. 대부분 호출하는 쪽의 레퍼런스가 없던 문제라 null조건 연산자로 해결했던..기억이 있네요

좋은 해결법 감사합니다!

**Comment by joonyle99** [comment]
현업에서도 자주 발생하는 문제가 참조 문제라고 들었습니다

C++에서도 유효하지 않은 주소를 가리키는 댕글링포인터 현상과 비슷하게, Null인 곳을 참조하려는 것은 자주 발생하는 문제인 것같아요.

이번에 제가 아카이브에 올린 포스팅도 비슷한 내용이거든요.

코드 로직상에서 유효하지 않은 참조의 오류를 예방하는 방법으로는, 그저 if문으로 잘 체크하는 습관을 들이는 게 중요한 것 같아요.

**Comment by rpopic2** [comment]
> 없다면 where를 통해서나 값을 제한 하는 방법도 좋을 것 같은데,

generic constraint로 `where T : notnull` 을 말씀하시는 걸까요? 이 상황에서도 쓸 수 있는지 궁금하네요


> is를 통한 null 조건도 좋아보입니다!

is null을 통한 패턴 매칭도 같은 코드로 컴파일되겠네요.


> 저의 경우엔.. 대부분 호출하는 쪽의 레퍼런스가 없던 문제라 null조건 연산자로 해결했던..기억이 있네요

`action?.Invoke()` 와 같이 말씀이신가요? 이것도 좋은 방법이라고 생각합니다! (개인적으로는 가독성과 브랜치를 숨긴다는 점 때문에 잘 안쓰려고 합니다)
