### ISSUE TITLE
joonyle99: [Error] Broken text PPtr in file - YAML 파일 수정하기

### ISSUE THREAD

**Issue by joonyle99** [BRIDGE-DEV/BRIDGE_Archive#14]
https://joonyle99.github.io/trouble_shooting/Trouble_Shooting-Broken-text-PPtr-in-file/

이번에 팀 작업하면서 Merge 과정에서 오류가 있었는지 Unity Animator에서 존재하지 않는 파일을 참조하는 상황이 발생했습니다. 이 문제를 YAML 파일을 직접 수정해 해결한 블로그 포스팅입니다.

**Comment by rpopic2** [comment]
흥미롭네요! 혹시 이전에 머지는 어떤 방식으로 진행하셨는지 궁금하네요

**Comment by fkdl0048** [comment]
좋은 글이네요 저도 마찬가지로 오류가 발생한 원인이 궁금합니다!

**Comment by joonyle99** [comment]
@rpopic2 @fkdl0048 

당시에 아트분과 같은 Player Animator 파일을 작업했는데, 그 과정에서

Player Animator에 할당된 Animation을 삭제했는데, Player Animator YAML파일에는 삭제한 Animation을 참조하는 부분이 남아있고, Animation파일만 삭제되어 발생한 문제인 것 같습니다.

+ 블로그 포스팅 내용 수정했습니다..! (Animator YAML 파일 분석 추가 및 오류 발생 원인 수정)
