### ISSUE TITLE
rpopic2: 브라우저 만들기

### ISSUE THREAD

**Issue by rpopic2** [BRIDGE-DEV/BRIDGE_Archive#15]
게임 개발관련 글이 아니라서 죄송하지만..
이번에 쓴 글이 이것밖에 없군요 ㅠㅠ

https://www.notion.so/blog-rpopic/Rust-4be80d940799427889e716676a88e767?pvs=4

**Comment by fkdl0048** [comment]
진짜 신기하네요.. Rust로 간단한 토이프로젝트를 해보는 경험이라니.. 부럽습니다ㅏ..

Rust가 항상 개발자들이 뽑는 좋은 언어 1등이면서 많이 사용은 안하고 있다고 들었습니다. 재 작년에 현중님이 Rust에 대해서 이야기 해주신 것도 기억이 나네요!

**직접 사용하기 위해** 브라우저를 터미널에서 만들었다니.. 찐 개발자이신 것 같습니다.

계속 업데이트 하실 생각인가요?

++ 요즘 로컬에 AI깔아서 사용한다고 하는데 혹시 사용하시나요? 

사용하신다면 후기가 궁금합니다!

**Comment by rpopic2** [comment]
일단 러스트는 프로그래밍하면서 즐거운 언어고, 너무 잘 만들어진 언어라는 생각이 들지만,
한편으로는 borrow checker의 강력한 제한때문에 생산성이 좀 떨어지는 느낌은 있는 것 같습니다. 하지만 한 번 배워볼만한 언어라고는 생각이 드네요. 프로그래밍을 새로운 관점에서 볼 수 있는 것 같습니다.

아마 업데이트는 틈나면 계속 하지 않을까 싶네요..ㅎㅎ (저를 위한..) 사소한 편의기능 추가는 할 것 같습니다

로컬에 ai같은 경우는... 저는 해본 적은 없습니다! 혹시 어떤 형태가 있나요?? 궁금하네요!

**Comment by joonyle99** [comment]
포스팅 잘 봤습니다,, 웹 브라우저를 개발하는 건 처음 봤습니다. Rust라는 언어도 들어만 보고 사용하시는 분은 처음 봤습니다. 정말 개발을 사랑하시는 게 느껴집니다. 저는 사용해 본 언어가 그리 많지 않아요. C++, C# 주력으로 쓰고 나머지는 정말 간단하게 학부에서 배우는 수준으로 js, java, lua 배웠던 게 전부인데 확실히 새로운 언어를 배울 때마다 프로그래밍 관점에서 새로운 시야가 트이게 되는 것 같아요. '실용주의 프로그래머`라는 책에서 말하길 1년에 한번은 새로운 언어를 배우라고 하는 게 기억나네요..ㅎㅎ
