### ISSUE TITLE
joonyle99: [unity] StateMachineBehaviour와 Animation Transition

### ISSUE THREAD

**Issue by joonyle99** [BRIDGE-DEV/BRIDGE_Archive#16]
별거 아닌 내용인 것 같지만,, 그래도 한 번 적어봤습니다..!
https://joonyle99.github.io/unity/Unity-StateMachineBehavior-&-Animation/

**Comment by fkdl0048** [comment]
글이 깔끔해서 잘 읽었습니다.

저도 예전에 비슷한 문제가 있었는데 당시엔 스파인으로 사용해서 해당 자동보간 기능을 이용했던 것 같네요 현재 FSM모델은 어떤 구조로 작성되어 있나요?

**Comment by joonyle99** [comment]
지금은 유니티에서 2D Animation, PSD Importer 등 2D 애니메이션에 필요한 기능을 제공해주지만
이전에는 정안님이 말씀하신 스파인과 같은 외부 툴을 이용해서 리깅하고 애니메이션을 제작해야 했다고 하더라구요.
FSM 모델이 뭔지 잘은 모르겠지만, 유니티에서 제공하는 StateMachineBehaviour를 사용하고 있습니다.

![unity_anim11](https://github.com/BRIDGE-DEV/BRIDGE_Archive/assets/67359781/4b725864-93c8-4038-ba5c-2046e47ce927)

**Comment by fkdl0048** [comment]
오,, 저는 FSM을 State패턴으로 직접 구현했던 기억이 있는데 유니티에서 제공을 해주는게 있군요 이번에 처음 알았습니다..

감사합니다!

**Comment by joonyle99** [comment]
@fkdl0048 
StateMachineBehavior 한 번 알아보세요! 부족한면이 좀 있는 것 같긴 하지만 되게 편리한것 같더라구요
