### ISSUE TITLE
유니티 에디터때문에 컴퓨터가 뜨거워 질 때

### ISSUE THREAD

**Issue by rpopic2** [BRIDGE-DEV/BRIDGE_Archive#24]
https://www.notion.so/blog-rpopic/c60f0a56fa0b4e4b98741695771c75e6?pvs=4

오랜만에 투고해봅니다.. ㅎㅎ

**Comment by fkdl0048** [comment]
노트북으로 유니티를 돌려본 적이 크게 없어서 잘 몰랐는데, 유니티 에디터에서도 프레임 때문에 발열이 생기는지 처음 알았네요..

저는 최근에 언리얼을 사용하면서 CPU을 업그레이드 했는데, 너무 높은 사양의 CPU로 올려서 컴파일 시기에 CPU온도가 100도를 찍는 문제가 있었습니다. 이를 해결하고자,.. CPU최대 출력을 70%로 낮추게 강제했습니다.. 이런 경험이 처음이라 너무 어이가 없었던.. ㅎㅎ
