### ISSUE TITLE
fkdl0048: 개발 블로그 운영 후기

### ISSUE THREAD

**Issue by fkdl0048** [BRIDGE-DEV/BRIDGE_Archive#25]
https://fkdl0048.github.io/blog/blog_Review/

개인적인 블로그 운영 후기입니다..^^

**Comment by rpopic2** [comment]
정말 매주 블로그 글쓰기는 쉽지도 않고, 글 정리하느라 지나치게 많은 시간을 쓰는 것 같아요.. 여기에는 간간히 투고하겠습니다.저도 단순 간단한 정보전달 글은 메뉴얼 보면 다 나오기도 하고, 메뉴얼이 더 정확하기 때문에 잘 쓰지도 보지도 않는 것 같아서 동감합니다.저는 찾기 힘들거나 제가 꼭 앞으로도 기억했으면 좋겠는 내용을 적는 것 같아요. 앗 이 내용 뭐였지? 싶을 때 블로그를 잠깐 보는 용도도 있고, 구하기 힘든 정보를 써서 다른 사람에게도 도움이 되는 용도로 쓰고 있어요뭔가 저도 보여주기식 블로그는 이제는 경쟁력도 없을 뿐더러 큰 도움이 안되는 것 같아서 그렇게는 하지 않으려 합니다글 잘 읽었습니다!On Apr 27, 2024, at 4:30 PM, Jeongan Lee ***@***.***> wrote:﻿
https://fkdl0048.github.io/blog/blog_Review/
개인적인 블로그 운영 후기입니다..^^
