### ISSUE TITLE
rpopic2: 생성자 안에서의 가상 함수

### ISSUE THREAD

**Issue by rpopic2** [BRIDGE-DEV/BRIDGE_Archive#4]
[블로그 링크](https://www.notion.so/blog-rpopic/416f778ba3ee42b6a6eb04aecb32adeb?pvs=4)

가장 최근에 쓰고 있었던 글인데요, 공교롭게도 생성자 안에서 가상 함수를 호출하지 말라는 정안님의 글을 보고 쓰게 된 글이네요!ㅋㅋ

C++과 C#의 행동이 반대라는 점 때문에 궁금해서 써본 글인데요, 각각 어셈블리와 IL을 분석하여 그 이유를 찾아내는 내용입니다.

틀린 정보 제보나 다른 생각을 가지고 계신분들, 혹은 내용이 이해가 안되시거나 질문 등등은 언제나 환영입니다. 댓글 달아주세요!

**Comment by fkdl0048** [comment]
저는 읽으면서 무심하게 c++과 다르구나 정도로 이해했는데 실제 내부 어셈블리 동작까지 보니까... 정말 대단하십니다..

궁금했던 부분을 너무 쉽게 이해할 수 있어서 좋은 정보 감사합니다..!

중간 중간 C#과 C++에 차이점, C++의 문법도 다 설명해주셔서 코드도 무리 없이 읽을 수 있었네요..

오류 코드도 좀 더 명확하게 알려주는 것 같고 c++과 c#의 근본적인 차이점에 대한 이해도 좀 넓어진 것 같습니다.

C#이 실제 인스턴스화된 객체에 대해 호출하는 동적 바인딩 부분도 그림으로 보다가 실제 어셈블리 코드로 보니 더 이해가 잘되고, 이어서 위에서 말한 c++과 c#은 그냥 차이가 있을 뿐이지 뭐가 더 낫다 보다는 상황에 유리한 언어가 있는 것이라는 생각이 드네요..

실제 virtual 구현되어 있는 부분의 vtable? 이거에 대한 궁금증이 생기기 시작했는데 리눅스 공부할 때 비슷한 걸 봤던 기억이...

또 빙산의 일각을 만난..ㅎ

너무 좋은 글을 1번으로 써주셔서 제가 쓸 글이 조금 겁나긴 하네요..

---

해당 이슈는 나중에 알아보기 쉽도록 이름 변경 후 코멘트가 완료되면 close해주시면 됩니다!

**Comment by rpopic2** [comment]
vtable의 기본 아이디어는 간단하게 말해서 각 객체마다 호출해야 할 함수가 어떤 것인지 적어두는 것입니다. 실제로 객체에 sizeof 연산자를 적용해 보면 아무 멤버 변수가 없어도 크기가 1이 아니라 8(혹은 그 이상)이 나오게 됩니다. vtable에 대한 포인터의 값이죠.

어떤 클래스에서 어떤 함수를 호출해야 하는지를 표로 만들어 두었다고 보시면 됩니다. 객체가 초기화 될 때, vtable의 해당 부분에 대한 포인터를 객체에 저장하게 됩니다.

결국 실제 호출할때는 우선 vtable에 대한 포인터를 따라가고, 그 다음에 실제 호출할 함수에 대한 포인터를 따라간 후, 실제 함수를 호출하게 됩니다. 총 2번의 포인터 따라가기가 필요합니다.

vtable 구현은 컴파일러가 상세를 정하게 됩니다! 유명한 c++ 컴파일러끼리는 모두 약속을 해서 통일시켜 놓았지만 C#의 모습은 다르다고 하더군요.

실제 어떻게 생겼는지는 아래 링크를 참고하시면 도움이 될 수 있겠네요. 블로그 링크인데 정리가 잘 되어있네요.
[링크](https://shaharmike.com/cpp/vtable-part1/)

**Comment by fkdl0048** [comment]
구조 이해하기에 정말 좋은 자료네요 실제로 궁금하시면 바로바로 내부까지 뜯어보시는 건가요?

처음 c언어 배울 때 생각나서 자꾸 물어보고 싶은게 생기는 것 같습니다 ㅎ..

**Comment by rpopic2** [comment]
네네 저는 보통 제가 먼저 뜯어보고 분석하고 도큐멘트 찾아보고 다른 사람들의 글까지 보는 편입니다!
