### ISSUE TITLE
fkdl0048: 스터디 회고록

### ISSUE THREAD

**Issue by fkdl0048** [BRIDGE-DEV/BRIDGE_Archive#5]
# fkdl0048: 스터디 회고록 

[글 링크](https://fkdl0048.github.io/daily/StudyRetrospect/)

첫 글로 무슨 글을 적으면 좋을 지 생각해봤는데, 첫 글이라 회고록을 적어봤습니다..

개인적인 생각이 많이 들어간 글이라 조금 난잡하긴 하지만, 생각 정리하고 앞으로 나가기 가장 좋은 형태가 회고록이 정말 좋다고 생각합니다..!

다양한 방법으로 작성해보고 있는데 이번엔 KPT으로 작성해봤는데요.. 궁금하신 내용이나 질문은 저도 언제든지 환영입니다!

**Comment by rpopic2** [comment]
제가 만든 지난 스터디들에서도 다들 중도하차 많이 하셔서 공감이 가네요 ㅋㅋㅋ


저의 경우에도 이런 문제였던 것 같습니다:
1. 원하는 것을 얻지 못함. 도움이 안 됨.
2. 하는 일에 우선순위가 밀림. 바쁨.

결국에는 더 이상 스터디가 도움되지 않는다고 느꼈다고 생각한 것 같습니다. 물론 그 문제에 대해서는 스터디에 참석하는 것이 자유이듯이 빠지는 것도 자유이며 빠지는 것에 대해 뭐라 할 권한도 없다고 생각합니다. 다만 이탈자를 줄이기 위해서는 그 사람들이 스터디에서 무엇을 얻기 위해 왔는지를 물어봐야겠다는 생각이 들었습니다.

우선 모집 공고문에서 비슷한 걸 얻고 싶은 사람을 구합니다. 그렇게 모인 사람들 사이에서도 얻고 싶은것은 분명 서로 다를 것 같습니다. OpenGL 스터디를 하면 어떤 사람은 엔진을 만들겠다는 열정과 원대한 꿈을 가질 수도 있고, 어떤 사람은 그저 컴퓨터 그래픽스에 대한 깊은 이해를 원할 수도 있고, 어떤 사람은 그냥 잘 모르지만 별 생각 없이 한번 찍먹하러 온 것일 수도 있습니다. 그래서 저는 각 멤버들의 생각을 물어보고, 조금씩이라도, 최대한 서로 원하는 것을 얻어갈 수 있도록 해야겠다고 생각했습니다. 스터디의 방향성의 흐트러지지 않는 범위 내에서요. 그래야 각자 원하는걸 얻어가서 스터디에 남아있지 않을까 생각했습니다.

아무튼 이 방법이 과연 이탈자를 줄이고 스터디원들을 만족시키는 목적을 달성할지는 다음에 한 번 해봐야 알겠네요 ㅋㅋ

좋은 글 잘 읽었습니다!

**Comment by fkdl0048** [comment]
> 다만 이탈자를 줄이기 위해서는 그 사람들이 스터디에서 무엇을 얻기 위해 왔는지를 물어봐야겠다는 생각이 들었습니다.

공감가는 말입니다.. 꼭 스터디가 아니더라도 프로젝트, 개인 공부 등 모든 도전에 있어서 개인이 달성하고자 하는 목표가 명확해지는 것이 중요하다고 생각되네요
