### ISSUE TITLE
fkdl0048: Unity MVP를 TDD로 구현하기

### ISSUE THREAD

**Issue by fkdl0048** [BRIDGE-DEV/BRIDGE_Archive#6]
# fkdl0048: Unity MVP를 TDD로 구현하기

[Unity MVP를 TDD로 구현하기](https://fkdl0048.github.io/unity/unity_in_MVPForTDD/)

제가 만든 모임인데 제가 늦어버렸네요..

저는 MVP패턴을 TDD..?로 만들어 봤습니다.

**Comment by rpopic2** [comment]
저도 최근에 유니티 UI를 어떻게 짜는게 효과적일지 고민이 많았었는데, 비슷한 고민을 하고 있던 것 같아 글 재밌게 보았습니다!

사실 TDD의 경우에는 게임업계에서는 거의 사용하고 있지 않는걸로 저는 알고 있긴 합니다. 그 뿐만 아니라 다른 업계에서도 잘 사용하지 않는걸로 저는 알고 있습니다.

저도 켄트 벡의 TDD 책을 읽었는데, 저 같은 경우에는:

1. 실제로 작동을 안 하는걸 확인하고,
2. 코드를 조금 수정하고,
3. 실제로 작동을 하는걸 확인하고

이 세 개의 프로세스가 흥미로웠던 것 같습니다. 물론 원본에는 맨 앞에 테스트를 먼저 짜는 항목이 하나 더 있지만, 굳이 TDD가 아니더라도 평소 개발할 때 쓸 수 있는 방법이라고 생각이 들었습니다. 이렇게 하니 필요없는 코드를 작성하지 않게 되고, 한 번에 많은 것을 짜는 게 아니라 책에서 말하는 "작은 발걸음"으로, 작은 단위로 일하는 방법도 배운 것 같습니다.

여기부터는 저의 그냥 극히 개인적인 생각인데요,, 당연히 제 생각이 틀릴 수도 있다는 말씀을 드리고 시작해 봅니다.

현재 저의 TDD에 대한 개인적인 생각은... 코드를 짜기 전 테스트를 짜는 것보다는, 필요에 의해, 코드 퇴화(regression)을 막기 위해 테스트를 짜는게 낫지 않나 하는게 저의 현재 생각입니다. 테스트를 먼저 작성하는 것이 적절하지 않은 상황도 있고 의미없는 테스트를 만들 수도 있고 불필요한 공수가 들 때 있다고 생각합니다. (하지만 TDD는 분명 한 번 배워볼 가치가 있는 방법론이라고 생각은 합니다.)

목(mock) 테스트는 좋지 않다는 이야기를 듣기도 했고... 저도 목이 필요한 경우는 테스트를 작성하려고 억지로 만드는(?) 느낌이라 애초에 작성할 필요가 없지 않나.. 생각을 해 봅니다. 저는 높은 테스트 커버리지가 꼭 제품의 품질을 보장하지는 않는다는 생각입니다.

쓰다 보니 너무 이야기가 길어졌군요! 이만 글 줄이겠습니다! 글 잘 보았습니다!

**Comment by fkdl0048** [comment]
저도 TDD관련 책을 읽고 흥미를 가지고 도전해본? 경험이였습니다 ㅎㅎ

저도 마찬가지로 TDD자체는 게임업계에서 많이 사용하지 않는다고 들었는데 왜 그런지에 대한 생각도 잘 정리되고, 단위 테스트가 더욱 필요한 이유?에 대해서 잘 알게된 것 같아서 좋았습니다.

저도 현중님과 같이 TDD를 왜 하는건지에 대한 개인적인 생각은 있었지만 TDD에 대한 가치는 항상 높게 평가 받는 것 같아서 궁금했기에 나름.. 도전이였습니다 ㅎ..

목 테스트의 경우도 러닝커브도 되게 크고, 쉽게 구현할 수 있지만 목을 만들기 위해서 코드를 짜게 되긴 하더라구요..

게임쪽에서 목을 만드는지 잘 모르겠지만 사실 더 좋은 테스트 서버같은 개념이 있기 때문에 잘 사용하지 않는걸까? 라는 생각도 해봤습니다

코멘트 감사합니다~!
