### ISSUE TITLE
fkdl0048: 게임 개발에서 PM이란?

### ISSUE THREAD

**Issue by fkdl0048** [BRIDGE-DEV/BRIDGE_Archive#9]
~~이번 글은 아마 과거 GDC나 게임 컨퍼런스를 듣고 느깐점을 정리하려고 합니다,~~

NDC인데 GDC라고 적었네요..

팀에서 PM을 맡고 있어서 관려해서 생각 정리가 될 것 같아서 작성했습니다!

[게임 개발에서 PM이란?](https://fkdl0048.github.io/daily/GamePM/)

**Comment by rpopic2** [comment]
글 잘 읽었습니다! PM에 대한 이야기라니 흥미롭네요! 팀을 위해서 열심히 공부하시는 모습이 멋있으시군요... 화이팅입니다!
